### ISSUE TITLE
Update files marked 'All rights reserved' to include the license

### ISSUE THREAD

**Issue by mattl** [ValveSoftware/ToGL#1]

**Comment by Plagman** [comment]
I would think the license at the top of the directoy is clear in that it applies to all the Valve files. Is there anything I'm missing here?

**Comment by mattl** [comment]
The files will eventually become separated from this repo. Putting the license details in each file will make things easier for everyone in the future.

**Comment by apples90730** [comment]
Te

**Comment by DarinM223** [comment]
I tried to fix this in my fork.... maybe you can check it out?

**Comment by Plagman** [comment]
If you send a pull request I'll gladly look at it!

**Comment by Plagman** [comment]
Thanks a lot!
